export const parkingSpots = [
  {
    id: '1',
    name: 'Tiefgarage Marienplatz',
    price: '256 €',
    location: 'indoor',
    address: 'Marienplatz 12, 80337 Munich',
    size: 'car',
    amenities: [],
    description: 'Parking Spot in the centrum of munich',
    imageSrc: '/parking-spot-1.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '2',
    name: 'Semi Public Parking Spot',
    price: '32 €',
    location: 'outdoor',
    address: 'Goethestraße 12, 80337 Munich',
    size: 'car',
    amenities: [],
    description: 'Through Schranke available',
    imageSrc: '/parking-spot-2.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '3',
    name: 'Maxvorstadt zentral',
    price: '120 €',
    location: 'indoor',
    address: 'Giselastraße 12, 80337 Munich',
    size: 'caravan',
    amenities: [],
    description: 'Parking Garage nearby Gisela Straße',
    imageSrc: '/parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '4',
    name: 'Backyard Parking',
    price: '80 €',
    location: 'outdoor',
    address: 'Koppenstraße 12, 10243 Berlin',
    size: 'car',
    amenities: ['electric-charging-available'],
    description: 'Easy parking in backyard',
    imageSrc: '/parking-spot-4.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '5',
    name: 'Zentraler Parkplatz Alexanderplatz',
    price: '256 €',
    location: 'indoor',
    address: 'Alexanderplatz 1, 10245 Berlin',
    size: 'car',
    amenities: [],
    description: 'Alexanderplatz Parking, Best Experience ever',
    imageSrc: '/parking-spot-5.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '6',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'car',
    amenities: [],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-6.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '7',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: '/parking-spot-7.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '8',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['electric-charging-available'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-8.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '9',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: '/parking-spot-9.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '10',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: [],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-10.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '11',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['electric-charging-available', 'power-socket'],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: '/parking-spot-11.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '12',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['power-socket'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-12.webp',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '13',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['electric-charging-available', 'power-socket'],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: '/parking-spot-13.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '14',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['power-socket'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-14.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '15',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['electric-charging-available', 'power-socket'],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: '/parking-spot-15.jpg',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '16',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    address: 'Schillerstraße 12, 80337 Munich',
    size: 'bike',
    amenities: ['power-socket'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: '/parking-spot-16.jpg',
    imageAlt: 'Front of plain black t-shirt.',
  },
]