export const parkingSpots = [
  {
    id: '1',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'bike',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-1.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '2',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    size: 'car',
    amenities: [],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-2.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '3',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'caravan',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '4',
    name: 'Basic Tee',
    price: '32 €',
    location: 'outdoor',
    size: 'bike',
    amenities: ['electric-charging-available'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-4.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '5',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'caravan',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '6',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    size: 'car',
    amenities: [],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-4.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '7',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'bike',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '8',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    size: 'bike',
    amenities: ['electric-charging-available'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-4.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '9',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'bike',
    amenities: [],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '10',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    size: 'bike',
    amenities: [],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-4.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
  {
    id: '11',
    name: 'Basic Tee 8-Pack',
    price: '256 €',
    location: 'indoor',
    size: 'bike',
    amenities: ['electric-charging-available', 'power-socket'],
    description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
    imageSrc: './parking-spot-3.webp',
    imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
  },
  {
    id: '12',
    name: 'Basic Tee',
    price: '32 €',
    location: 'indoor',
    size: 'bike',
    amenities: ['power-socket'],
    description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
    imageSrc: './parking-spot-4.jpeg',
    imageAlt: 'Front of plain black t-shirt.',
  },
]